<?php use yii\helpers\Html; use yii\helpers\Json; $rtmp=$source->getRtmpUrl(); $key=$source->getStreamKey(); ?>
<div class="panel panel-default"><div class="panel-heading"><strong><i class="fa fa-rss"></i> Live-Studio</strong></div><div class="panel-body">
<h3><?= Html::encode($session->title) ?></h3>
<div class="alert alert-info"><strong>1.</strong> Trage Server und Streamschlüssel in OBS ein. <strong>2.</strong> Starte dort die Übertragung. HumHub erkennt Start und Ende automatisch.</div>
<div class="form-group"><label>Streamserver</label><div class="input-group"><input id="pt-live-server" class="form-control" readonly value="<?= Html::encode($rtmp) ?>"><span class="input-group-btn"><button class="btn btn-default pt-copy" data-copy="pt-live-server" type="button"><i class="fa fa-copy"></i> Kopieren</button></span></div></div>
<div class="form-group"><label>Streamschlüssel</label><div class="input-group"><input id="pt-live-key" type="password" class="form-control" readonly value="<?= Html::encode($key) ?>"><span class="input-group-btn"><button class="btn btn-default" id="pt-live-reveal" type="button"><i class="fa fa-eye"></i></button><button class="btn btn-default pt-copy" data-copy="pt-live-key" type="button"><i class="fa fa-copy"></i> Kopieren</button></span></div></div>
<p class="text-warning"><i class="fa fa-lock"></i> Behandle den Streamschlüssel wie ein Passwort. Er bleibt für deine künftigen Livestreams gleich.</p>
<div id="pt-live-state"><?php if($session->status==='scheduled'): ?><div class="alert alert-info"><i class="fa fa-calendar"></i> Geplant für <?= Yii::$app->formatter->asDatetime($session->start_datetime) ?>.</div><?php elseif($session->status==='preparing'): ?><div class="alert alert-warning"><i class="fa fa-clock-o"></i> Warte auf das Sendesignal von OBS …</div><?php elseif($session->status==='live'): ?><div class="alert alert-danger"><i class="fa fa-circle"></i> Deine Sendung ist LIVE. Zum Beenden stoppst du die Übertragung in OBS.</div><?php elseif($session->status==='ending'): ?><div class="alert alert-info"><i class="fa fa-spinner fa-spin"></i> Die Aufzeichnung wird verarbeitet …</div><?php elseif($session->status==='failed'): ?><div class="alert alert-danger">Die automatische Verarbeitung ist fehlgeschlagen. Die Administration wurde informiert.</div><?php else: ?><div class="alert alert-success">Die Sendung wurde als Video gespeichert.</div><?php endif; ?></div>
</div></div>
<?php $statusUrl=$this->context->contentContainer->createUrl('/peertube/live/status',['id'=>$session->id]); $this->registerJs("document.getElementById('pt-live-reveal').onclick=function(){var e=document.getElementById('pt-live-key');e.type=e.type==='password'?'text':'password'};document.querySelectorAll('.pt-copy').forEach(function(b){b.onclick=function(){var e=document.getElementById(b.dataset.copy);navigator.clipboard.writeText(e.value);b.innerHTML='<i class=\"fa fa-check\"></i> Kopiert';};});(function poll(){fetch(".\yii\helpers\Json::htmlEncode($statusUrl).",{credentials:'same-origin',headers:{Accept:'application/json'}}).then(function(r){return r.json()}).then(function(d){var e=document.getElementById('pt-live-state');if(!e)return;if(d.status==='live')e.innerHTML='<div class=\"alert alert-danger\"><i class=\"fa fa-circle\"></i> Deine Sendung ist LIVE. Zum Beenden stoppst du die Übertragung in OBS.</div>';else if(d.status==='ending')e.innerHTML='<div class=\"alert alert-info\"><i class=\"fa fa-spinner fa-spin\"></i> Die Aufzeichnung wird verarbeitet …</div>';else if(d.status==='completed'&&d.redirectUrl){window.location.href=d.redirectUrl;return;}else if(d.status==='failed')e.innerHTML='<div class=\"alert alert-danger\">Die automatische Verarbeitung ist fehlgeschlagen. Die Administration wurde informiert.</div>';if(['scheduled','preparing','live','ending'].indexOf(d.status)>=0)setTimeout(poll,3000);}).catch(function(){setTimeout(poll,5000);});})();"); ?>
